spring.application.name=customer
server.port=${PORT:8091}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
spring.data.redis.database=0
spring.datasource.url=jdbc:postgresql://ep-wandering-glitter-b52iz61a-pooler.c-7.us-east-2.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_W0dCMabDik9P
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.forma_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



